//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_ESTADO
    {
        public CAD_ESTADO()
        {
            this.CAD_CIDADE = new HashSet<CAD_CIDADE>();
        }
    
        public int IDC_CAD_ESTADO { get; set; }
        public string SIG_ESTADO { get; set; }
        public string NOM_ESTADO { get; set; }
    
        public virtual ICollection<CAD_CIDADE> CAD_CIDADE { get; set; }
    }
}
