//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_SOLO
    {
        public CAD_SOLO()
        {
            this.CAD_PARCELA = new HashSet<CAD_PARCELA>();
        }
    
        public int IDC_CAD_SOLO { get; set; }
        public string NOM_SOLO { get; set; }
        public Nullable<double> VAR_CAPACIDADE_CAMPO { get; set; }
        public Nullable<double> VAR_PONTO_MURCHA { get; set; }
        public Nullable<double> DEN_APARENTE { get; set; }
        public Nullable<double> VAR_LIMITE { get; set; }
        public Nullable<double> VAR_KS { get; set; }
        public Nullable<int> CAD_FAZENDA_IDC_CAD_FAZENDA { get; set; }
    
        public virtual CAD_FAZENDA CAD_FAZENDA { get; set; }
        public virtual ICollection<CAD_PARCELA> CAD_PARCELA { get; set; }
    }
}
