//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_GOTEJADOR
    {
        public CAD_GOTEJADOR()
        {
            this.CAD_PARCELA = new HashSet<CAD_PARCELA>();
        }
    
        public int IDC_CAD_GOTEJADOR { get; set; }
        public string NOM_GOTEJADOR { get; set; }
        public Nullable<double> VAZ_GOTEJADOR { get; set; }
        public Nullable<double> VAR_ESPACAMENTO_GOTEJADORES { get; set; }
        public Nullable<double> VAR_ESPACAMENTO_LINHAS_LATERAIS { get; set; }
        public Nullable<double> LAR_FAIXA_MOLHADA { get; set; }
        public Nullable<double> VAR_UNIFORMIDADE { get; set; }
        public Nullable<double> VAR_LAMINA { get; set; }
        public int CAD_FAZENDA_IDC_CAD_FAZENDA { get; set; }
    
        public virtual CAD_FAZENDA CAD_FAZENDA { get; set; }
        public virtual ICollection<CAD_PARCELA> CAD_PARCELA { get; set; }
    }
}
