//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_PARCELA
    {
        public CAD_PARCELA()
        {
            this.CAD_UMIDADE = new HashSet<CAD_UMIDADE>();
            this.CAD_PRECIPITACAO = new HashSet<CAD_PRECIPITACAO>();
            this.CAD_UMIDADE1 = new HashSet<CAD_UMIDADE>();
            this.REG_MANEJO = new HashSet<REG_MANEJO>();
        }
    
        public string NOM_PARCELA { get; set; }
        public Nullable<double> ARE_PARCELA { get; set; }
        public string VAR_PLUVIOMETRO { get; set; }
        public Nullable<double> VAR_UMIDADE_SOLO_PLANTIO { get; set; }
        public Nullable<double> VAR_ESTRESSE_EXCEDIDO { get; set; }
        public Nullable<int> CAD_OUTORGA_IDC_CAD_OUTORGA { get; set; }
        public int CAD_CULTURA_IDC_CAD_CULTURA { get; set; }
        public Nullable<int> CAD_PIVO_CENTRAL_IDC_CAD_PIVO_CENTRAL { get; set; }
        public Nullable<int> CAD_GOTEJADOR_IDC_CAD_GOTEJADOR { get; set; }
        public System.DateTime DAT_PLANTIO { get; set; }
        public int IDC_CAD_PARCELA { get; set; }
        public int CAD_SOLO_IDC_CAD_SOLO { get; set; }
    
        public virtual CAD_CULTURA CAD_CULTURA { get; set; }
        public virtual CAD_GOTEJADOR CAD_GOTEJADOR { get; set; }
        public virtual CAD_OUTORGA CAD_OUTORGA { get; set; }
        public virtual ICollection<CAD_UMIDADE> CAD_UMIDADE { get; set; }
        public virtual CAD_PIVO_CENTRAL CAD_PIVO_CENTRAL { get; set; }
        public virtual CAD_SOLO CAD_SOLO { get; set; }
        public virtual ICollection<CAD_PRECIPITACAO> CAD_PRECIPITACAO { get; set; }
        public virtual ICollection<CAD_UMIDADE> CAD_UMIDADE1 { get; set; }
        public virtual ICollection<REG_MANEJO> REG_MANEJO { get; set; }
    }
}
