//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_CIDADE
    {
        public CAD_CIDADE()
        {
            this.CAD_FAZENDA = new HashSet<CAD_FAZENDA>();
        }
    
        public int IDC_CAD_CIDADE { get; set; }
        public string NOM_CIDADE { get; set; }
        public int CAD_ESTADO_IDC_CAD_ESTADO { get; set; }
    
        public virtual CAD_ESTADO CAD_ESTADO { get; set; }
        public virtual ICollection<CAD_FAZENDA> CAD_FAZENDA { get; set; }
    }
}
