//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_ADMINISTRADOR
    {
        public int ID_ADMINISTRADOR { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public Nullable<bool> ATIVO { get; set; }
    }
}
