//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_OUTORGA
    {
        public CAD_OUTORGA()
        {
            this.CAD_FASE_OUTORGA = new HashSet<CAD_FASE_OUTORGA>();
            this.CAD_PARCELA = new HashSet<CAD_PARCELA>();
        }
    
        public int IDC_CAD_OUTORGA { get; set; }
        public string NOM_OUTORGA { get; set; }
        public int CAD_FAZENDA_IDC_CAD_FAZENDA { get; set; }
    
        public virtual ICollection<CAD_FASE_OUTORGA> CAD_FASE_OUTORGA { get; set; }
        public virtual CAD_FAZENDA CAD_FAZENDA { get; set; }
        public virtual ICollection<CAD_PARCELA> CAD_PARCELA { get; set; }
    }
}
