//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_FASE_OUTORGA
    {
        public int IDC_CAD_FASE_OUTORGA { get; set; }
        public Nullable<System.DateTime> DAT_INICIO { get; set; }
        public string NOM_FASE_OUTORGA { get; set; }
        public Nullable<System.DateTime> DAT_FIM { get; set; }
        public Nullable<int> LIM_FASE_OUTORGA { get; set; }
        public int CAD_OUTORGA_IDC_CAD_OUTORGA { get; set; }
    
        public virtual CAD_OUTORGA CAD_OUTORGA { get; set; }
    }
}
