//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_PRECIPITACAO
    {
        public int IDC_CAD_PRECIPITACAO { get; set; }
        public Nullable<System.DateTime> DAT_PRECIPITACAO { get; set; }
        public Nullable<double> VAR_PRECIPITACAO { get; set; }
        public int CAD_PARCELA_IDC_CAD_PARCELA { get; set; }
    
        public virtual CAD_PARCELA CAD_PARCELA { get; set; }
    }
}
