//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_CLIENTE
    {
        public CAD_CLIENTE()
        {
            this.CAD_FAZENDA = new HashSet<CAD_FAZENDA>();
            this.CAD_USUARIO = new HashSet<CAD_USUARIO>();
        }
    
        public int IDC_CAD_CLIENTE { get; set; }
        public string CNF_USUARIO_CLIENTE { get; set; }
        public string NOM_CLIENTE { get; set; }
        public string CNF_EMAIL_CLIENTE { get; set; }
        public string CNF_SENHA_CLIENTE { get; set; }
        public Nullable<byte> CNF_ATIVO_CLIENTE { get; set; }
    
        public virtual ICollection<CAD_FAZENDA> CAD_FAZENDA { get; set; }
        public virtual ICollection<CAD_USUARIO> CAD_USUARIO { get; set; }
    }
}
