//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_FASE_CULTURA
    {
        public int IDC_CAD_FASE_CULTURA { get; set; }
        public string NOM_FASE_CULTURA { get; set; }
        public Nullable<double> VAR_KC { get; set; }
        public Nullable<double> PRF_RAIZ { get; set; }
        public Nullable<double> ARE_SOMBREADA { get; set; }
        public int CAD_CULTURA_IDC_CAD_CULTURA { get; set; }
        public int NUM_INICIO { get; set; }
        public int NUM_FIM { get; set; }
        public Nullable<double> VAR_PREF_RADICULAR { get; set; }
    
        public virtual CAD_CULTURA CAD_CULTURA { get; set; }
    }
}
