//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_CLIMA
    {
        public int IDC_CAD_CLIMA { get; set; }
        public System.DateTime DAT_CLIMA { get; set; }
        public Nullable<double> TMP_CLIMA_MAX { get; set; }
        public Nullable<double> TMP_CLIMA_MIN { get; set; }
        public Nullable<double> TMP_CLIMA_MEDIA { get; set; }
        public Nullable<double> VAR_UMIDADE_RELATIVA { get; set; }
        public Nullable<double> VEL_VENTO { get; set; }
        public Nullable<double> VAR_PRECIPITACAO_TOTAL { get; set; }
        public Nullable<double> VAR_RADIACAO { get; set; }
        public int CAD_FAZENDA_IDC_CAD_FAZENDA { get; set; }
    
        public virtual CAD_FAZENDA CAD_FAZENDA { get; set; }
    }
}
