//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_USUARIO
    {
        public decimal IDC_USUARIO { get; set; }
        public string NOM_USUARIO { get; set; }
        public string NUM_MATRICULA { get; set; }
        public string SENHA_USUARIO { get; set; }
        public System.DateTime DTH_CRIACAO { get; set; }
        public System.DateTime DTH_ALTERACAO { get; set; }
    }
}
