//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_MOTOBOMBA_TARIFA
    {
        public int IDC_CAD_MOTOBOMBA_TARIFA { get; set; }
        public string NOM_TARIFA { get; set; }
        public Nullable<System.TimeSpan> HOR_INICIO_TARIFA { get; set; }
        public Nullable<System.TimeSpan> HOR_FIM_TARIFA { get; set; }
        public Nullable<double> VAL_TARIFA { get; set; }
        public int CAD_MOTOBOMBA_IDC_CAD_MOTOBOMBA { get; set; }
    
        public virtual CAD_MOTOBOMBA CAD_MOTOBOMBA { get; set; }
    }
}
