//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_USUARIO
    {
        public int IDC_CAD_USUARIO { get; set; }
        public string NUM_MATRICULA { get; set; }
        public string NOM_USUARIO { get; set; }
        public string CNF_SENHA { get; set; }
        public Nullable<System.DateTime> DAT_CRIACAO { get; set; }
        public int CAD_CLIENTE_IDC_CAD_CLIENTE { get; set; }
        public Nullable<System.DateTime> DAT_ALTERACAO { get; set; }
        public Nullable<int> CAD_FAZENDA_IDC_CAD_FAZENDA { get; set; }
    
        public virtual CAD_CLIENTE CAD_CLIENTE { get; set; }
        public virtual CAD_FAZENDA CAD_FAZENDA { get; set; }
    }
}
