//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_IRRIGACAO
    {
        public int IDC_CAD_IRRIGACAO { get; set; }
        public System.DateTime DAT_IRRIGACAO { get; set; }
        public Nullable<double> TMO_IRRIGACAO_PIVO { get; set; }
        public Nullable<double> TMO_IRRIGACAO_GOTEJO { get; set; }
        public Nullable<System.TimeSpan> TMO_IRRIGACAO_INICIO { get; set; }
        public Nullable<double> VOL_IRRIGACAO { get; set; }
        public Nullable<double> VOL_CONSUMIDO { get; set; }
        public Nullable<double> VAR_VALOR_ENERGETICO { get; set; }
        public Nullable<byte> VAR_FERTIRRIGACAO { get; set; }
        public int CAD_PARCELA_IDC_CAD_PARCELA { get; set; }
        public int CAD_MOTOBOMBA_IDC_CAD_MOTOBOMBA { get; set; }
        public int CAD_RESERVATORIO_IDC_CAD_RESERVATORIO { get; set; }
        public Nullable<System.TimeSpan> TMO_IRRIGACAO_FIM { get; set; }
    
        public virtual CAD_MOTOBOMBA CAD_MOTOBOMBA { get; set; }
        public virtual CAD_PARCELA CAD_PARCELA { get; set; }
        public virtual CAD_RESERVATORIO CAD_RESERVATORIO { get; set; }
    }
}
