//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_ADMINISTRADOR
    {
        public int IDC_CAD_ADMINISTRADOR { get; set; }
        public string USUARIO { get; set; }
        public string NOM_USUARIO { get; set; }
        public string CFG_EMAIL_ADMINISTRADOR { get; set; }
        public string CFG_SENHA_ADMINISTRADOR { get; set; }
        public Nullable<byte> CFG_ATIVO_ADMINISTRADOR { get; set; }
    }
}
