//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_MOTOBOMBA
    {
        public CAD_MOTOBOMBA()
        {
            this.CAD_MOTOBOMBA_TARIFA = new HashSet<CAD_MOTOBOMBA_TARIFA>();
            this.CAD_RESERVATORIO_DIARIO = new HashSet<CAD_RESERVATORIO_DIARIO>();
            this.CAD_IRRIGACAO = new HashSet<CAD_IRRIGACAO>();
        }
    
        public int IDC_CAD_MOTOBOMBA { get; set; }
        public string NOM_MOTOBOMBA { get; set; }
        public Nullable<int> VAR_POTENCIA { get; set; }
        public Nullable<double> VAR_CONSUMO { get; set; }
        public Nullable<double> VAZ_MOTOBOMBA { get; set; }
        public string VAR_TARIFAS { get; set; }
        public int CAD_FAZENDA_IDC_CAD_FAZENDA { get; set; }
    
        public virtual CAD_FAZENDA CAD_FAZENDA { get; set; }
        public virtual ICollection<CAD_MOTOBOMBA_TARIFA> CAD_MOTOBOMBA_TARIFA { get; set; }
        public virtual ICollection<CAD_RESERVATORIO_DIARIO> CAD_RESERVATORIO_DIARIO { get; set; }
        public virtual ICollection<CAD_IRRIGACAO> CAD_IRRIGACAO { get; set; }
    }
}
