//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_PIVO_CENTRAL
    {
        public CAD_PIVO_CENTRAL()
        {
            this.CAD_PARCELA = new HashSet<CAD_PARCELA>();
        }
    
        public int IDC_CAD_PIVO_CENTRAL { get; set; }
        public Nullable<double> VEL_100_PIVO { get; set; }
        public Nullable<System.TimeSpan> TEMP_DIARIO_MAX { get; set; }
        public Nullable<double> DIS_RAIO_TOTAL { get; set; }
        public Nullable<double> VAR_VAO_BALANCO { get; set; }
        public Nullable<double> VAZ_PIVO { get; set; }
        public Nullable<double> VAR_EFICIENCIA { get; set; }
        public Nullable<double> VAR_LAMINA { get; set; }
        public Nullable<int> CAD_MODELO_PIVO_IDC_CAD_MODELO_PIVO { get; set; }
        public int CAD_FAZENDA_IDC_CAD_FAZENDA { get; set; }
    
        public virtual CAD_FAZENDA CAD_FAZENDA { get; set; }
        public virtual CAD_MODELO_PIVO CAD_MODELO_PIVO { get; set; }
        public virtual ICollection<CAD_PARCELA> CAD_PARCELA { get; set; }
    }
}
