//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidrocontroll.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hidrocontrollEntities : DbContext
    {
        public hidrocontrollEntities()
            : base("name=hidrocontrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAD_ADMINISTRADOR> CAD_ADMINISTRADOR { get; set; }
        public DbSet<CAD_USUARIO> CAD_USUARIO { get; set; }
    }
}
